compile:
	@javac BookAnalysisG06.java

doc:
	@cd cs296BookAnalysis; \
	javadoc *.java

clean:
	@rm -rf *.class
	@rm -rf cs296BookAnalysis/*.class
	@rm -rf cs296BookAnalysis/*.html
	@rm -rf cs296BookAnalysis/*.css
	@rm -rf cs296BookAnalysis/cs296BookAnalysis
	@rm -rf cs296BookAnalysis/package-list
	@rm -rf cs296BookAnalysis/resources
	@rm -rf *~
	@rm -rf cs296BookAnalysis/*~